name: TP9 Actions

on:
  push:
    tags:
      - "V1.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image yo
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            lemalgache/tpdockerfile:${{ github.ref }}
            lemalgache/tpdockerfile:latest

      - name: Logout from DockerHub
        uses: docker/logout-action@v1
